name: gregstreak.com
favicon: null
layout_spectrum: 0.17534
typography_spectrum: 0.14579
title: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dce0e9'
    - '#bbbfc2'
    - '#999999'
    - '#291455'
    - '#4b2c91'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
